--Extra Data Validations added

USE ROLE DATA_TRANSFORM_ROLE;
USE DATABASE DATA_PLATFORM;
USE SCHEMA SEMANTIC;
USE SCHEMA LANDING;
USE WAREHOUSE INGEST_WH_XS;

--create Stored Procedure for DQ Validations

CREATE OR REPLACE PROCEDURE SEMANTIC.SP_DQ_VALIDATE()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    SRC_COUNT NUMBER;
    TGT_COUNT NUMBER;
BEGIN

------------------------------------------------
-- SOURCE COUNT
------------------------------------------------

SELECT COUNT(*) INTO :SRC_COUNT
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;

------------------------------------------------
-- TARGET COUNT
------------------------------------------------

SELECT COUNT(*) INTO :TGT_COUNT
FROM SEMANTIC.DT_DIM_CUSTOMER;

------------------------------------------------
-- INSERT INTO AUDIT LOG
------------------------------------------------

INSERT INTO SEMANTIC.DQ_AUDIT_LOG (
    SOURCE_COUNT,
    TARGET_COUNT,
    STATUS,
    RUN_TS
)
VALUES (
    :SRC_COUNT,
    :TGT_COUNT,
    CASE
        WHEN :SRC_COUNT = :TGT_COUNT THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP()
);

------------------------------------------------
-- NULL CHECK FOR PRIMARY KEY
------------------------------------------------

INSERT INTO SEMANTIC.DQ_AUDIT_LOG (
    SOURCE_COUNT,
    TARGET_COUNT,
    STATUS,
    RUN_TS
)
SELECT
    COUNT(*),
    0,
    'FAIL_NULL_PK',
    CURRENT_TIMESTAMP()
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
WHERE CUSTOMER_ID IS NULL;

------------------------------------------------
-- DUPLICATE CHECK
------------------------------------------------

INSERT INTO SEMANTIC.DQ_AUDIT_LOG (
    SOURCE_COUNT,
    TARGET_COUNT,
    STATUS,
    RUN_TS
)
SELECT
    COUNT(*),
    0,
    'FAIL_DUPLICATE_CUSTOMER',
    CURRENT_TIMESTAMP()
FROM (
    SELECT CUSTOMER_ID
    FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
    GROUP BY CUSTOMER_ID
    HAVING COUNT(*) > 1
);

------------------------------------------------
-- EMAIL VALIDATION
------------------------------------------------

INSERT INTO SEMANTIC.DQ_AUDIT_LOG (
    SOURCE_COUNT,
    TARGET_COUNT,
    STATUS,
    RUN_TS
)
SELECT
    COUNT(*),
    0,
    'FAIL_INVALID_EMAIL',
    CURRENT_TIMESTAMP()
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
WHERE EMAIL NOT LIKE '%@%.%';

RETURN 'DQ VALIDATION COMPLETED';

END;
$$;

--call procedure Manually
CALL SEMANTIC.SP_DQ_VALIDATE();

ALTER TASK SEMANTIC.TASK_RUN_DQ RESUME;

SHOW TASKS IN SCHEMA SEMANTIC;

SELECT *
FROM SEMANTIC.DQ_AUDIT_LOG
ORDER BY RUN_TS DESC;


USE ROLE DATA_TRANSFORM_ROLE;
USE DATABASE DATA_PLATFORM;
USE WAREHOUSE INGEST_WH_XS;
USE SCHEMA LANDING;

ALTER TASK TASK_PROCESS_CUSTOMER RESUME;
ALTER TASK TASK_LOAD_CUSTOMER RESUME;



ALTER TASK PIPELINE.TASK_REFRESH_STAGING RESUME;
ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION RESUME;

SHOW TASKS IN DATABASE DATA_PLATFORM;

SELECT COUNT(*) FROM LANDING.CUSTOMER_LANDING;

SELECT COUNT(*) FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;

SELECT * FROM SEMANTIC.DT_DIM_CUSTOMER;

SELECT * 
FROM SEMANTIC.DQ_AUDIT_LOG
ORDER BY RUN_TS DESC;


--suspend all tasks

ALTER TASK TASK_PROCESS_CUSTOMER SUSPEND;
ALTER TASK TASK_LOAD_CUSTOMER SUSPEND;


ALTER TASK PIPELINE.TASK_REFRESH_STAGING SUSPEND;
ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION SUSPEND;

ALTER TASK SEMANTIC.TASK_RUN_DQ SUSPEND;