--Week 4

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;
GRANT CREATE TABLE ON SCHEMA DATA_PLATFORM.SEMANTIC TO ROLE DATA_TRANSFORM_ROLE;
GRANT CREATE TABLE ON SCHEMA DATA_PLATFORM.TRANSFORMATION TO ROLE DATA_TRANSFORM_ROLE;
GRANT CREATE STREAM ON SCHEMA DATA_PLATFORM.SEMANTIC TO ROLE DATA_TRANSFORM_ROLE;
GRANT CREATE TASK ON SCHEMA DATA_PLATFORM.SEMANTIC TO ROLE DATA_TRANSFORM_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_TRANSFORM_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE INGEST_WH_XS TO ROLE DATA_TRANSFORM_ROLE;


USE ROLE DATA_TRANSFORM_ROLE;
USE WAREHOUSE INGEST_WH_XS;
USE DATABASE DATA_PLATFORM;
USE SCHEMA LANDING;

--Create Dim Table 

CREATE OR REPLACE TABLE SEMANTIC.DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    REGION STRING,
    CUSTOMER_TYPE STRING,
    EFFECTIVE_DATE DATE,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY)
);

--Creating Fact Table
CREATE OR REPLACE TABLE SEMANTIC.FACT_CUSTOMER_ACTIVITY (
    FACT_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID NUMBER,
    CREATED_DATE DATE,
    LOAD_TS TIMESTAMP
);

--Initial Load to Dim Table
INSERT INTO SEMANTIC.DIM_CUSTOMER (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    REGION,
    CUSTOMER_TYPE,
    EFFECTIVE_DATE,
    LOAD_TS
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    REGION,
    CUSTOMER_TYPE,
    CURRENT_DATE(),
    CURRENT_TIMESTAMP()
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;

--Populating Fact Table

INSERT INTO SEMANTIC.FACT_CUSTOMER_ACTIVITY (
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CREATED_DATE,
    LOAD_TS
)
SELECT
    D.CUSTOMER_KEY,
    T.CUSTOMER_ID,
    T.CREATED_DATE,
    CURRENT_TIMESTAMP()
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED T
JOIN SEMANTIC.DIM_CUSTOMER D
ON T.CUSTOMER_ID = D.CUSTOMER_ID;

--Dynamic Table for DIM Customer

CREATE OR REPLACE DYNAMIC TABLE SEMANTIC.DT_DIM_CUSTOMER
TARGET_LAG = '1 minute'
WAREHOUSE = INGEST_WH_XS
AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    REGION,
    CUSTOMER_TYPE,
    CURRENT_DATE() AS EFFECTIVE_DATE,
    CURRENT_TIMESTAMP() AS LOAD_TS
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;

--Dynamic Table for Fact
CREATE OR REPLACE DYNAMIC TABLE SEMANTIC.DT_FACT_CUSTOMER
TARGET_LAG = '1 minute'
WAREHOUSE = INGEST_WH_XS
AS
SELECT
    CUSTOMER_ID,
    CREATED_DATE,
    CURRENT_TIMESTAMP() AS LOAD_TS
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;


--Create DQ Framework
CREATE OR REPLACE TABLE SEMANTIC.DQ_AUDIT_LOG (
    RUN_ID NUMBER AUTOINCREMENT,
    SOURCE_COUNT NUMBER,
    TARGET_COUNT NUMBER,
    STATUS STRING,
    RUN_TS TIMESTAMP
);



--Automate DQ Check

CREATE OR REPLACE TASK SEMANTIC.TASK_RUN_DQ
WAREHOUSE = INGEST_WH_XS
SCHEDULE = '5 minute'
AS
CALL SEMANTIC.SP_DQ_VALIDATE();


--Resuming All the suspended Tasks
ALTER TASK TASK_PROCESS_CUSTOMER RESUME;
ALTER TASK TASK_LOAD_CUSTOMER RESUME;


ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION RESUME;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING RESUME;


ALTER TASK SEMANTIC.TASK_RUN_DQ RESUME;


SELECT COUNT(*) FROM SEMANTIC.DT_DIM_CUSTOMER;
SELECT COUNT(*) FROM SEMANTIC.DT_FACT_CUSTOMER;

SELECT * FROM SEMANTIC.DT_DIM_CUSTOMER;
SELECT * FROM SEMANTIC.DT_FACT_CUSTOMER;

USE DATABASE DATA_PLATFORM;
USE SCHEMA SEMANTIC;

SHOW DYNAMIC TABLES;

SELECT * FROM SEMANTIC.DQ_AUDIT_LOG
ORDER BY RUN_TS DESC;


SHOW TASKS IN SCHEMA PIPELINE;


--Suspend All the Tasks

ALTER TASK TASK_PROCESS_CUSTOMER SUSPEND;
ALTER TASK TASK_LOAD_CUSTOMER SUSPEND;


ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION SUSPEND;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING SUSPEND;


ALTER TASK SEMANTIC.TASK_RUN_DQ SUSPEND;

SHOW TASKS;

SHOW TASKS IN SCHEMA PIPELINE;



SELECT *
FROM SEMANTIC.V_CUSTOMER_SUMMARY;


SELECT CUSTOMER_ID,
       CREATED_DATE,
       CUSTOMER_TYPE
FROM DATA_PLATFORM.TRANSFORMATION.CUSTOMER_TRANSFORMED
ORDER BY CUSTOMER_ID DESC;
