CREATE OR REPLACE WAREHOUSE INGEST_WH_XS
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE DATA_PLATFORM;
CREATE OR REPLACE SCHEMA DATA_PLATFORM.LANDING;

CREATE OR REPLACE STORAGE INTEGRATION S3_STORAGE_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::260621207295:role/snowflake_s3_ingest_role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://company-data-landing-s3/landing/');

DESC INTEGRATION S3_STORAGE_INT;


CREATE OR REPLACE FILE FORMAT DATA_PLATFORM.LANDING.CSV_FILE_FORMAT_STD
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL','null');

CREATE OR REPLACE STAGE DATA_PLATFORM.LANDING.S3_LANDING_STAGE
  URL = 's3://company-data-landing-s3/landing/'
  STORAGE_INTEGRATION = S3_STORAGE_INT
  FILE_FORMAT = DATA_PLATFORM.LANDING.CSV_FILE_FORMAT_STD;


LIST @DATA_PLATFORM.LANDING.S3_LANDING_STAGE;


CREATE OR REPLACE TABLE DATA_PLATFORM.LANDING.CUSTOMER_LANDING (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  COUNTRY STRING,
  CREATED_DATE DATE
);

COPY INTO DATA_PLATFORM.LANDING.CUSTOMER_LANDING
FROM @DATA_PLATFORM.LANDING.S3_LANDING_STAGE/customer/
ON_ERROR = 'ABORT_STATEMENT';

SELECT * FROM DATA_PLATFORM.LANDING.CUSTOMER_LANDING;


CREATE OR REPLACE ROLE PLATFORM_INGEST_ROLE;

GRANT USAGE ON WAREHOUSE INGEST_WH_XS TO ROLE PLATFORM_INGEST_ROLE;
GRANT USAGE ON DATABASE DATA_PLATFORM TO ROLE PLATFORM_INGEST_ROLE;
GRANT USAGE ON SCHEMA DATA_PLATFORM.LANDING TO ROLE PLATFORM_INGEST_ROLE;
GRANT SELECT, INSERT ON TABLE DATA_PLATFORM.LANDING.CUSTOMER_LANDING TO ROLE PLATFORM_INGEST_ROLE;
GRANT USAGE ON STAGE DATA_PLATFORM.LANDING.S3_LANDING_STAGE TO ROLE PLATFORM_INGEST_ROLE;

GRANT ROLE PLATFORM_INGEST_ROLE TO USER NIKHILSHETTAR1810;

USE ROLE PLATFORM_INGEST_ROLE;
USE WAREHOUSE INGEST_WH_XS;

LIST @DATA_PLATFORM.LANDING.S3_LANDING_STAGE;
SELECT COUNT(*) FROM DATA_PLATFORM.LANDING.CUSTOMER_LANDING;
SELECT * FROM DATA_PLATFORM.LANDING.CUSTOMER_LANDING;
SHOW WAREHOUSES;

