--Week 3

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE DATA_TRANSFORM_ROLE;

GRANT USAGE ON DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;

GRANT CREATE SCHEMA ON DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE DATA_PLATFORM TO ROLE DATA_TRANSFORM_ROLE;

GRANT USAGE ON WAREHOUSE INGEST_WH_XS TO ROLE DATA_TRANSFORM_ROLE;

GRANT ROLE DATA_TRANSFORM_ROLE TO USER nikhilshettar1810;

USE ROLE DATA_TRANSFORM_ROLE;
USE DATABASE DATA_PLATFORM;
USE WAREHOUSE INGEST_WH_XS;
USE SCHEMA LANDING;

ALTER TASK TASK_PROCESS_CUSTOMER RESUME;
ALTER TASK TASK_LOAD_CUSTOMER RESUME;

SELECT * FROM LANDING.CUSTOMER_FINAL;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA TRANSFORMATION;
CREATE OR REPLACE SCHEMA SEMANTIC;


--creation of staging table

CREATE OR REPLACE TABLE STAGING.CUSTOMER_STG (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    CREATED_DATE DATE,
    LOAD_TS TIMESTAMP
);

--create stream 
CREATE OR REPLACE STREAM STAGING.STREAM_CUSTOMER_FINAL
ON TABLE LANDING.CUSTOMER_FINAL;

CREATE OR REPLACE SCHEMA PIPELINE;



--created task for staging refresh
CREATE OR REPLACE TASK PIPELINE.TASK_REFRESH_STAGING
WAREHOUSE = INGEST_WH_XS
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGING.STREAM_CUSTOMER_FINAL')
AS
BEGIN

MERGE INTO STAGING.CUSTOMER_STG T
USING (
    SELECT *
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY CUSTOMER_ID
                   ORDER BY LOAD_TS DESC
               ) AS RN
        FROM STAGING.STREAM_CUSTOMER_FINAL
        WHERE METADATA$ACTION IN ('INSERT','UPDATE')
    )
    WHERE RN = 1
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    T.FIRST_NAME = UPPER(S.FIRST_NAME),
    T.LAST_NAME = UPPER(S.LAST_NAME),
    T.EMAIL = LOWER(S.EMAIL),
    T.COUNTRY = S.COUNTRY,
    T.CREATED_DATE = S.CREATED_DATE,
    T.LOAD_TS = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
VALUES (
    S.CUSTOMER_ID,
    UPPER(S.FIRST_NAME),
    UPPER(S.LAST_NAME),
    LOWER(S.EMAIL),
    S.COUNTRY,
    S.CREATED_DATE,
    CURRENT_TIMESTAMP()
);

END;

--creation of transformation table for transformation layer

CREATE OR REPLACE TABLE TRANSFORMATION.CUSTOMER_TRANSFORMED (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    CREATED_DATE DATE,
    CUSTOMER_TYPE STRING,
    REGION STRING,
    LOAD_TS TIMESTAMP
);

--creating stream on staging layer
CREATE OR REPLACE STREAM TRANSFORMATION.STREAM_CUSTOMER_STG
ON TABLE STAGING.CUSTOMER_STG;

--creating stored procedure for transformation 
CREATE OR REPLACE PROCEDURE DATA_PLATFORM.TRANSFORMATION.SP_TRANSFORM_CUSTOMER()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

MERGE INTO DATA_PLATFORM.TRANSFORMATION.CUSTOMER_TRANSFORMED T
USING (
    SELECT *
    FROM (
        SELECT 
            S.CUSTOMER_ID,
            S.FIRST_NAME,
            S.LAST_NAME,
            S.EMAIL,
            S.COUNTRY,
            S.CREATED_DATE,
            S.LOAD_TS,
            ROW_NUMBER() OVER (
                PARTITION BY S.CUSTOMER_ID
                ORDER BY S.LOAD_TS DESC
            ) AS RN
        FROM DATA_PLATFORM.STAGING.CUSTOMER_STG S
    )
    WHERE RN = 1
) S
ON T.CUSTOMER_ID = S.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    T.FIRST_NAME = S.FIRST_NAME,
    T.LAST_NAME  = S.LAST_NAME,
    T.EMAIL      = S.EMAIL,
    T.COUNTRY    = S.COUNTRY,
    T.CREATED_DATE = S.CREATED_DATE,
    T.CUSTOMER_TYPE =
        CASE
            WHEN S.CREATED_DATE <= DATEADD(YEAR, -1, CURRENT_DATE())
            THEN 'EXISTING_CUSTOMER'
            ELSE 'NEW_CUSTOMER'
        END,
    T.REGION =
        CASE
            WHEN S.COUNTRY IN ('USA','Canada')
            THEN 'NORTH_AMERICA'
            ELSE 'OTHER'
        END,
    T.LOAD_TS = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    COUNTRY,
    CREATED_DATE,
    CUSTOMER_TYPE,
    REGION,
    LOAD_TS
)
VALUES (
    S.CUSTOMER_ID,
    S.FIRST_NAME,
    S.LAST_NAME,
    S.EMAIL,
    S.COUNTRY,
    S.CREATED_DATE,
    CASE
        WHEN S.CREATED_DATE <= DATEADD(YEAR, -1, CURRENT_DATE())
        THEN 'EXISTING_CUSTOMER'
        ELSE 'NEW_CUSTOMER'
    END,
    CASE
        WHEN S.COUNTRY IN ('USA','Canada')
        THEN 'NORTH_AMERICA'
        ELSE 'OTHER'
    END,
    CURRENT_TIMESTAMP()
);

RETURN 'TRANSFORMATION COMPLETED SUCCESSFULLY';

END;
$$;


--manual testing of the procedure created

CALL TRANSFORMATION.SP_TRANSFORM_CUSTOMER();

--automating procedure using task
CREATE OR REPLACE TASK PIPELINE.TASK_RUN_TRANSFORMATION
WAREHOUSE = INGEST_WH_XS
AFTER PIPELINE.TASK_REFRESH_STAGING
AS
CALL TRANSFORMATION.SP_TRANSFORM_CUSTOMER();

ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION RESUME;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING RESUME;

--Semantic Layer
CREATE OR REPLACE VIEW SEMANTIC.V_CUSTOMER_SUMMARY AS
SELECT
    REGION,
    CUSTOMER_TYPE,
    COUNT(*) AS TOTAL_CUSTOMERS
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
GROUP BY REGION, CUSTOMER_TYPE;

--created view on top of semantic layer
CREATE OR REPLACE VIEW SEMANTIC.V_CUSTOMER_DETAILS AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
    EMAIL,
    REGION,
    CUSTOMER_TYPE,
    CREATED_DATE
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;


USE ROLE ACCOUNTADMIN;
USE DATABASE DATA_PLATFORM;
USE SCHEMA PIPELINE;

SHOW TASKS;

ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION RESUME;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING RESUME;

SELECT *
FROM LANDING.CUSTOMER_FINAL
WHERE CUSTOMER_ID >= 3001
ORDER BY CUSTOMER_ID;

SELECT SYSTEM$STREAM_HAS_DATA('STAGING.STREAM_CUSTOMER_FINAL');

SELECT *
FROM STAGING.CUSTOMER_STG
WHERE CUSTOMER_ID >= 3001;

SHOW TASKS IN SCHEMA PIPELINE;

SELECT SYSTEM$STREAM_HAS_DATA('STAGING.STREAM_CUSTOMER_FINAL');

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC;

USE ROLE ACCOUNTADMIN;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE DATA_TRANSFORM_ROLE;


ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION SUSPEND;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING SUSPEND;

ALTER TASK PIPELINE.TASK_RUN_TRANSFORMATION RESUME;
ALTER TASK PIPELINE.TASK_REFRESH_STAGING RESUME;


SELECT SYSTEM$STREAM_HAS_DATA('STAGING.STREAM_CUSTOMER_FINAL');

SELECT * FROM STAGING.CUSTOMER_STG;

SELECT * FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;

SELECT CUSTOMER_TYPE, COUNT(*)
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
WHERE CUSTOMER_ID >= 3001
GROUP BY CUSTOMER_TYPE;

SELECT REGION, COUNT(*)
FROM TRANSFORMATION.CUSTOMER_TRANSFORMED
WHERE CUSTOMER_ID >= 3001
GROUP BY REGION;

SELECT *
FROM SEMANTIC.V_CUSTOMER_SUMMARY;


ALTER TASK PIPELINE.TASK_REFRESH_STAGING SUSPEND;


SELECT SYSTEM$STREAM_HAS_DATA('STAGING.STREAM_CUSTOMER_FINAL');

SELECT * FROM STAGING.CUSTOMER_STG;

SELECT * FROM TRANSFORMATION.CUSTOMER_TRANSFORMED;


SELECT *
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE QUERY_TEXT ILIKE '%CUSTOMER_TRANSFORMED%'
ORDER BY START_TIME DESC;

show tasks;

use schema landing;

show tasks;

ALTER TASK TASK_PROCESS_CUSTOMER SUSPEND;
ALTER TASK TASK_LOAD_CUSTOMER SUSPEND;