--Week 2

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE INGEST_WH_XS;
CREATE OR REPLACE DATABASE DATA_PLATFORM;
USE DATABASE DATA_PLATFORM;
CREATE OR REPLACE SCHEMA LANDING;
USE SCHEMA LANDING;


--creating External Stage
CREATE OR REPLACE STORAGE INTEGRATION S3_STORAGE_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::260621207295:role/snowflake_s3_ingest_role'
STORAGE_ALLOWED_LOCATIONS = ('s3://company-data-landing-s3/landing/');


--File Format Creation
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT_STD
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','null');

--stage creation
CREATE OR REPLACE STAGE S3_LANDING_STAGE
URL = 's3://company-data-landing-s3/landing/'
STORAGE_INTEGRATION = S3_STORAGE_INT
FILE_FORMAT = CSV_FILE_FORMAT_STD;


DESC INTEGRATION S3_STORAGE_INT;

LIST @S3_LANDING_STAGE;

--Created Landing Table
CREATE OR REPLACE TABLE CUSTOMER_LANDING (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    CREATED_DATE DATE,
    FILE_NAME STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

--Created Final Table 
CREATE OR REPLACE TABLE CUSTOMER_FINAL (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    CREATED_DATE DATE,
    LOAD_TS TIMESTAMP
);


--Created table to load Rejected Records
CREATE TABLE IF NOT EXISTS CUSTOMER_REJECTED (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    COUNTRY STRING,
    CREATED_DATE STRING,
    ERROR_MESSAGE STRING,
    FILE_NAME STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


--Created Audit Table 
CREATE OR REPLACE TABLE INGEST_AUDIT_LOG (
    FILE_NAME STRING,
    ROWS_PARSED NUMBER,
    ROWS_LOADED NUMBER,
    ROWS_REJECTED NUMBER,
    STATUS STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

--Created stream for continuous ingestion
CREATE OR REPLACE STREAM CUSTOMER_LANDING_STREAM
ON TABLE CUSTOMER_LANDING
APPEND_ONLY = TRUE;


--bulk load using copy command
COPY INTO CUSTOMER_LANDING
FROM (
    SELECT
        TRY_TO_NUMBER($1),
        $2,
        $3,
        $4,
        $5,
        TRY_TO_DATE($6),
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @S3_LANDING_STAGE/customer/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT_STD)
ON_ERROR = CONTINUE;



--create notification integration

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION SQS_NOTIFICATION_INT
TYPE = QUEUE
DIRECTION = INBOUND
NOTIFICATION_PROVIDER = AWS_SQS
ENABLED = TRUE
AWS_SQS_ARN = 'arn:aws:sqs:us-east-1:<your-account>:snowflake-auto-ingest-queue'
AWS_SQS_ROLE_ARN = 'arn:aws:iam::<your-account>:role/snowflake_s3_ingest_role';


---verify integration
DESC NOTIFICATION INTEGRATION SQS_NOTIFICATION_INT;


---create snowpipe using autoingest

CREATE OR REPLACE PIPE CUSTOMER_AUTO_PIPE
AUTO_INGEST = TRUE
NOTIFICATION_INTEGRATION = SQS_NOTIFICATION_INT
AS
COPY INTO CUSTOMER_LANDING
FROM (
    SELECT
        TRY_TO_NUMBER($1),
        $2,
        $3,
        $4,
        $5,
        TRY_TO_DATE($6),
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @S3_LANDING_STAGE/customer/
)
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT_STD)
ON_ERROR = CONTINUE;

---validate the pipeline status

SELECT SYSTEM$PIPE_STATUS('CUSTOMER_AUTO_PIPE');

--create processing task to move data from landing to main table

CREATE OR REPLACE TASK TASK_PROCESS_CUSTOMER
WAREHOUSE = INGEST_WH_XS
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CUSTOMER_LANDING_STREAM')
AS
BEGIN


    INSERT INTO CUSTOMER_REJECTED
    SELECT
        CUSTOMER_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        COUNTRY,
        CREATED_DATE,
        'INVALID DATA',
        FILE_NAME,
        CURRENT_TIMESTAMP()
    FROM CUSTOMER_LANDING_STREAM
    WHERE CUSTOMER_ID IS NULL
       OR CREATED_DATE IS NULL;


    CREATE OR REPLACE TEMP TABLE TMP_VALID AS
    SELECT *
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (
                   PARTITION BY CUSTOMER_ID
                   ORDER BY LOAD_TS DESC
               ) RN
        FROM CUSTOMER_LANDING_STREAM
        WHERE CUSTOMER_ID IS NOT NULL
          AND CREATED_DATE IS NOT NULL
    )
    WHERE RN = 1;


    MERGE INTO CUSTOMER_FINAL T
    USING TMP_VALID S
    ON T.CUSTOMER_ID = S.CUSTOMER_ID

    WHEN MATCHED THEN UPDATE SET
        T.FIRST_NAME = S.FIRST_NAME,
        T.LAST_NAME = S.LAST_NAME,
        T.EMAIL = S.EMAIL,
        T.COUNTRY = S.COUNTRY,
        T.CREATED_DATE = S.CREATED_DATE,
        T.LOAD_TS = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED THEN INSERT
    VALUES (
        S.CUSTOMER_ID,
        S.FIRST_NAME,
        S.LAST_NAME,
        S.EMAIL,
        S.COUNTRY,
        S.CREATED_DATE,
        CURRENT_TIMESTAMP()
    );


    INSERT INTO INGEST_AUDIT_LOG
    SELECT
        FILE_NAME,
        COUNT(*),
        SUM(CASE WHEN CUSTOMER_ID IS NOT NULL
                  AND CREATED_DATE IS NOT NULL THEN 1 ELSE 0 END),
        SUM(CASE WHEN CUSTOMER_ID IS NULL
                  OR CREATED_DATE IS NULL THEN 1 ELSE 0 END),
        'SUCCESS',
        CURRENT_TIMESTAMP()
    FROM CUSTOMER_LANDING_STREAM
    GROUP BY FILE_NAME;

END;

--enable the task
ALTER TASK TASK_PROCESS_CUSTOMER RESUME;


--validation for Full load
SELECT * FROM CUSTOMER_FINAL;
SELECT * FROM INGEST_AUDIT_LOG;

--validation incremental load
SELECT * FROM CUSTOMER_FINAL ORDER BY CUSTOMER_ID;

SELECT CUSTOMER_ID, COUNT(*)
FROM CUSTOMER_FINAL
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

--validation error file
SELECT * FROM CUSTOMER_REJECTED;

--stream validation
SELECT SYSTEM$STREAM_HAS_DATA('CUSTOMER_LANDING_STREAM');

--pipe validation
SELECT SYSTEM$PIPE_STATUS('CUSTOMER_AUTO_PIPE');


--to pause the snowpipe

ALTER PIPE CUSTOMER_AUTO_PIPE SET PIPE_EXECUTION_PAUSED = TRUE;

